[server]
host = "0.0.0.0"
port = 9339
max_connections = 100

[crypto]
encryption_key = "fhsd6f86f67rt8fw78fw789we78r9789wer6re"
nonce = "nonce"

[game]
major_version = 0
build = 0
content_version = 0

[console]
figlet_text = "PySupercell"
figlet_font = "slant"
